os:
  - linux
  - osx

language: d

d: dmd
language: d
sudo: false
dist: trusty

services:
  - mongodb
  - redis-server

addons:
  apt:
    packages:
      - libevent-dev
      - libssl-dev
      - pkg-config
      - zlib1g-dev
#      - libsodium-dev
before_install:
# osx
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libsodium; fi
  
## linux
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git clone -b 1.0.12 --single-branch git://github.com/jedisct1/libsodium.git ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd libsodium; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./autogen.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./configure --disable-dependency-tracking --enable-minimal; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make install ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /sbin/ldconfig ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ..; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm -fr libsodium; fi

script: dub --build=unittest --compiler=$DC
#sudo: false
