language: d
d: dmd
before_install:
- sudo add-apt-repository -y ppa:chris-lea/libsodium
- sudo apt-get update -qq
- sudo apt-get install -qq libevent-dev libssl-dev libsqlite3-dev libsodium-dev
script: dub --build=unittest --compiler=$DC
#sudo: false